services:
  central:
    image: ghcr.io/thesteau/relay-centralizer-central:latest
    env_file:
      - ./.env
    ports:
      - "6555:8000"
    volumes:
      - ./data/backups:/backups
      - ./data/staging:/staging
      - ./secrets:/run/secrets
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
